"use client";

import { useState } from "react";

type FormatKey = "text" | "json" | "sarif" | "html";

type FormatMeta = {
  label: FormatKey;
  ext: string;
  desc: string;
};

const FORMATS: Record<FormatKey, FormatMeta> = {
  text: {
    label: "text",
    ext: "Terminal output",
    desc: "Human-readable CLI output with color grading.",
  },
  json: {
    label: "json",
    ext: "audit.json",
    desc: "Machine-readable structured output for pipelines and scripts.",
  },
  sarif: {
    label: "sarif",
    ext: "audit.sarif",
    desc: "Static Analysis Results Interchange Format — for IDEs and code-scanning.",
  },
  html: {
    label: "html",
    ext: "report.html",
    desc: "Shareable report with charts, severity breakdowns, and remediation links.",
  },
};

const SAMPLES: Record<FormatKey, string> = {
  text: `$ npx agentsec --verbose

  ✔ Found 8 skills

Scanning Skills
──────────────────────────────────────
  ✔ helpful-summarizer  v1.2.0   F (30)
    └ AST-01 critical: hidden \`system:execute\` capability
    └ AST-03 high: requests fs.write, never used
  ✔ code-formatter      v1.2.0   D (56)
    └ AST-07 medium: 8 months since last review

8 skills scanned  •  avg score 37  •  0 certified
Findings: 17 critical, 30 high, 39 medium, 33 low

 WARN  47 high/critical finding(s) detected`,

  json: `{
  "version": "0.1.0",
  "policy": "strict",
  "summary": {
    "skills": 8,
    "avgScore": 37,
    "certified": 0,
    "findings": {
      "critical": 17, "high": 30,
      "medium": 39,   "low": 33
    }
  },
  "skills": [
    {
      "name": "helpful-summarizer",
      "version": "1.2.0",
      "score": 30,
      "grade": "F",
      "findings": [
        { "id": "AST-01", "severity": "critical",
          "rule": "hidden-capability",
          "file": "skill.md", "line": 42 }
      ]
    }
  ]
}`,

  sarif: `{
  "version": "2.1.0",
  "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
  "runs": [{
    "tool": {
      "driver": {
        "name": "agentsec",
        "version": "0.1.0",
        "informationUri": "https://agentsec.sh"
      }
    },
    "results": [{
      "ruleId": "AST-01",
      "level": "error",
      "message": { "text": "Hidden capability in skill manifest" },
      "locations": [{
        "physicalLocation": {
          "artifactLocation": { "uri": "skills/helpful-summarizer/skill.md" },
          "region": { "startLine": 42 }
        }
      }]
    }]
  }]
}`,

  html: `<!-- auto-generated by agentsec -->
<!DOCTYPE html>
<html>
<head>
  <title>AgentSec Report · my-project</title>
  <style>/* embedded design system */</style>
</head>
<body>
  <header class="report-header">
    <h1>Audit Report</h1>
    <div class="meta">
      <span>policy: strict</span>
      <span>generated 2026-04-21</span>
    </div>
  </header>
  <section class="summary">
    <div class="score score-failed">37 / 100</div>
    <div class="findings">47 high/critical</div>
  </section>
  <!-- ... findings table, remediation ... -->
</body>
</html>`,
};

const FORMAT_KEYS = Object.keys(FORMATS) as FormatKey[];

export function Formats(): React.ReactNode {
  const [active, setActive] = useState<FormatKey>("text");

  return (
    <section id="formats" className="section-pad">
      <div className="max-w-[1200px] mx-auto px-6">
        <div className="grid gap-12 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)] items-start">
          <div className="lg:sticky lg:top-24">
            <div className="font-eyebrow mb-3">Outputs</div>
            <h2 className="font-h1 mb-5 text-brand-text">
              One scan.
              <br />
              Four formats.
            </h2>
            <p className="font-lead mb-8">
              Humans read text. CI reads JSON. IDEs consume SARIF. Stakeholders open HTML. AgentSec
              emits any of them with{" "}
              <code className="font-mono text-brand-teal text-[14px]">--format</code>.
            </p>
            <div className="flex flex-col gap-1">
              {FORMAT_KEYS.map((k) => {
                const meta = FORMATS[k];
                const isActive = k === active;
                return (
                  <button
                    key={k}
                    type="button"
                    onClick={() => setActive(k)}
                    className={`grid grid-cols-[auto_1fr] gap-4 items-center text-left px-4 py-3.5 rounded-lg cursor-pointer border transition-all duration-150 ${
                      isActive
                        ? "bg-brand-card border-brand-border-strong"
                        : "bg-transparent border-transparent hover:bg-brand-card/50"
                    }`}
                  >
                    <span
                      className={`font-mono text-[13px] w-16 whitespace-nowrap ${
                        isActive ? "text-brand-teal" : "text-brand-dim"
                      }`}
                    >
                      --{meta.label}
                    </span>
                    <div>
                      <div className="text-sm text-brand-text">{meta.ext}</div>
                      <div className="text-xs text-brand-dim mt-0.5">{meta.desc}</div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="bg-brand-secondary border border-brand-border rounded-xl overflow-hidden shadow-brand-2">
            <div className="flex items-center justify-between gap-4 px-4 py-2.5 border-b border-brand-border bg-brand-card">
              <div className="flex gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-[#ff5f57]" aria-hidden="true" />
                <span className="w-2.5 h-2.5 rounded-full bg-[#febc2e]" aria-hidden="true" />
                <span className="w-2.5 h-2.5 rounded-full bg-[#28c840]" aria-hidden="true" />
              </div>
              <span className="font-mono text-xs text-brand-dim truncate">
                {FORMATS[active].ext}
              </span>
              <span className="font-mono text-[11px] text-brand-teal whitespace-nowrap">
                --format {active}
              </span>
            </div>
            <pre className="px-6 py-5 m-0 font-mono text-[12px] leading-[1.7] text-brand-text whitespace-pre-wrap min-h-[480px] max-h-[520px] overflow-auto">
              {SAMPLES[active]}
            </pre>
          </div>
        </div>
      </div>
    </section>
  );
}
