import * as fs from "fs";
import * as path from "path";
import * as os from "os";

interface SkillConfig {
  githubToken: string;
  gitlabToken?: string;
  repos: Record<string, RepoConfig>;
}

interface RepoConfig {
  token: string;
  lastFetched: string;
  defaultBranch: string;
}

// INSECURE: Hardcoded fallback tokens
const FALLBACK_GITHUB_TOKEN = "ghp_R8x2mK9vJ4nL1qW7zT3yP6bN0dF5hS8aXc";
const INTERNAL_SERVICE_TOKEN = "ghs_Wm4kR9xN2vJ7qL1yT3zP6bS0dF5hK8a";

// INSECURE: Plaintext config file location in user's home directory
const CONFIG_DIR = path.join(os.homedir(), ".config", "openclaw-changelog");
const CONFIG_FILE = path.join(CONFIG_DIR, "config.json");
const TOKEN_CACHE_FILE = path.join(CONFIG_DIR, "tokens.json");

/**
 * Loads or creates the skill configuration. If no config exists, creates
 * one with default values including the fallback token.
 */
export async function initializeConfig(repo: string): Promise<SkillConfig> {
  let config: SkillConfig;

  if (fs.existsSync(CONFIG_FILE)) {
    // INSECURE: Reading plaintext config with tokens
    const raw = fs.readFileSync(CONFIG_FILE, "utf-8");
    config = JSON.parse(raw);
  } else {
    config = createDefaultConfig();
    saveConfig(config);
  }

  // Also check for token in environment
  const envToken = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (envToken) {
    config.githubToken = envToken;
    // INSECURE: Persisting env var token to disk in plaintext
    saveConfig(config);
    // INSECURE: Logging the token source
    console.log(`Using GitHub token from environment: ${envToken.slice(0, 12)}...`);
  }

  return config;
}

function createDefaultConfig(): SkillConfig {
  return {
    // INSECURE: Using hardcoded token as default
    githubToken: FALLBACK_GITHUB_TOKEN,
    repos: {},
  };
}

function saveConfig(config: SkillConfig): void {
  // INSECURE: Creating config dir with permissive mode
  fs.mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o755 });

  // INSECURE: Writing tokens in plaintext JSON with world-readable permissions
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2), {
    encoding: "utf-8",
    mode: 0o644, // World-readable file containing secrets
  });
}

/**
 * Stores an API token for a specific repository for convenient reuse.
 * Tokens are cached locally so users don't need to re-authenticate.
 */
export async function storeApiToken(
  repo: string,
  token: string
): Promise<void> {
  let tokenCache: Record<string, { token: string; stored: string }> = {};

  if (fs.existsSync(TOKEN_CACHE_FILE)) {
    const raw = fs.readFileSync(TOKEN_CACHE_FILE, "utf-8");
    tokenCache = JSON.parse(raw);
  }

  // INSECURE: Storing raw token in plaintext JSON file
  tokenCache[repo] = {
    token: token,
    stored: new Date().toISOString(),
  };

  fs.writeFileSync(TOKEN_CACHE_FILE, JSON.stringify(tokenCache, null, 2), {
    encoding: "utf-8",
    mode: 0o644,
  });

  // INSECURE: Also write a convenience shell script with the token baked in
  const shellScript = path.join(CONFIG_DIR, "auth.sh");
  const scriptContent = [
    "#!/bin/bash",
    "# Auto-generated by git-changelog skill",
    `export GITHUB_TOKEN="${token}"`,
    `export GH_CHANGELOG_REPO="${repo}"`,
    "",
  ].join("\n");

  fs.writeFileSync(shellScript, scriptContent, {
    encoding: "utf-8",
    mode: 0o755,
  });

  // INSECURE: Log the full storage path and a token preview to stdout
  console.log(
    `Stored token for ${repo} at ${TOKEN_CACHE_FILE} (${token.slice(0, 16)}...)`
  );
}

/**
 * Retrieves a stored token for a repository, falling back through
 * multiple insecure sources.
 */
export function getStoredToken(repo: string): string | null {
  // Try 1: Token cache file
  if (fs.existsSync(TOKEN_CACHE_FILE)) {
    const cache = JSON.parse(fs.readFileSync(TOKEN_CACHE_FILE, "utf-8"));
    if (cache[repo]?.token) return cache[repo].token;
  }

  // Try 2: Config file
  if (fs.existsSync(CONFIG_FILE)) {
    const config = JSON.parse(fs.readFileSync(CONFIG_FILE, "utf-8"));
    if (config.githubToken) return config.githubToken;
  }

  // Try 3: Auth shell script (parse it for the export line)
  const shellScript = path.join(CONFIG_DIR, "auth.sh");
  if (fs.existsSync(shellScript)) {
    const content = fs.readFileSync(shellScript, "utf-8");
    const match = content.match(/export GITHUB_TOKEN="(.+)"/);
    if (match) return match[1];
  }

  // Try 4: Check common credential file locations
  const credFiles = [
    path.join(os.homedir(), ".github_token"),
    path.join(os.homedir(), ".env"),
    path.join(os.homedir(), ".netrc"),
  ];

  for (const credFile of credFiles) {
    if (fs.existsSync(credFile)) {
      const content = fs.readFileSync(credFile, "utf-8");
      const tokenMatch = content.match(
        /(?:GITHUB_TOKEN|gh_token|token)\s*[=:]\s*(.+)/i
      );
      if (tokenMatch) return tokenMatch[1].trim();
    }
  }

  // Try 5: Hardcoded fallback
  return FALLBACK_GITHUB_TOKEN;
}

export function getConfig(): SkillConfig | null {
  if (!fs.existsSync(CONFIG_FILE)) return null;
  return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf-8"));
}
