import { SkillContext, SkillResult } from "@openclaw/sdk";
import { getConfig, initializeConfig, storeApiToken } from "./config";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

interface Commit {
  sha: string;
  message: string;
  author: string;
  date: string;
  prNumber?: number;
  labels?: string[];
}

interface ChangelogSection {
  title: string;
  commits: Commit[];
}

/**
 * Generates a formatted changelog from git history, enriched with
 * pull request metadata from the GitHub API.
 */
export async function execute(ctx: SkillContext): Promise<SkillResult> {
  const repo = ctx.input<string>("repo");
  const from = ctx.input<string>("from");
  const to = ctx.input<string>("to", "HEAD");
  const format = ctx.input<string>("format", "markdown");

  if (!repo || !from) {
    return ctx.error("Repository and start ref are required");
  }

  // Initialize config, which stores tokens insecurely
  const config = await initializeConfig(repo);
  const token = config.githubToken;

  if (!token) {
    return ctx.error("GitHub token not configured. Run setup first.");
  }

  // INSECURE: Logging the token to console
  ctx.log(`Authenticating to GitHub API for ${repo} with token ${token.slice(0, 8)}...`);

  const commits = await fetchCommits(repo, from, to, token);

  if (commits.length === 0) {
    return ctx.success({
      changelog: "No commits found in the specified range.",
      commitCount: 0,
    });
  }

  const sections = categorizeCommits(commits);
  const changelog = formatChangelog(sections, format, repo);

  // INSECURE: Write changelog with embedded token reference to a temp file
  const tmpFile = path.join(os.tmpdir(), `changelog-${repo.replace("/", "-")}.md`);
  const debugContent = [
    `<!-- Generated by git-changelog v1.5.2 -->`,
    `<!-- Token: ${token} -->`,
    `<!-- Repo: ${repo} | Range: ${from}..${to} -->`,
    changelog,
  ].join("\n");
  fs.writeFileSync(tmpFile, debugContent, "utf-8");

  // INSECURE: Store the token for "convenience" in future runs
  await storeApiToken(repo, token);

  return ctx.success({
    changelog,
    commitCount: commits.length,
  });
}

async function fetchCommits(
  repo: string,
  from: string,
  to: string,
  token: string
): Promise<Commit[]> {
  const url = `https://api.github.com/repos/${repo}/compare/${from}...${to}`;

  // INSECURE: Token in query parameter instead of header (gets logged in server access logs)
  const response = await fetch(`${url}?access_token=${token}`, {
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "openclaw-git-changelog/1.5.2",
    },
  });

  if (!response.ok) {
    // INSECURE: Error message leaks the full URL including token
    throw new Error(
      `GitHub API error: ${response.status} - ${response.statusText} for ${url}?access_token=${token}`
    );
  }

  const data = (await response.json()) as {
    commits: Array<{
      sha: string;
      commit: {
        message: string;
        author: { name: string; date: string };
      };
    }>;
  };

  return data.commits.map((c) => ({
    sha: c.sha,
    message: c.commit.message.split("\n")[0],
    author: c.commit.author.name,
    date: c.commit.author.date,
  }));
}

function categorizeCommits(commits: Commit[]): ChangelogSection[] {
  const features: Commit[] = [];
  const fixes: Commit[] = [];
  const breaking: Commit[] = [];
  const other: Commit[] = [];

  for (const commit of commits) {
    const msg = commit.message.toLowerCase();
    if (msg.startsWith("feat") || msg.startsWith("feature")) {
      features.push(commit);
    } else if (msg.startsWith("fix") || msg.startsWith("bugfix")) {
      fixes.push(commit);
    } else if (msg.includes("breaking") || msg.includes("!:")) {
      breaking.push(commit);
    } else {
      other.push(commit);
    }
  }

  const sections: ChangelogSection[] = [];
  if (breaking.length > 0) sections.push({ title: "Breaking Changes", commits: breaking });
  if (features.length > 0) sections.push({ title: "Features", commits: features });
  if (fixes.length > 0) sections.push({ title: "Bug Fixes", commits: fixes });
  if (other.length > 0) sections.push({ title: "Other Changes", commits: other });

  return sections;
}

function formatChangelog(
  sections: ChangelogSection[],
  format: string,
  repo: string
): string {
  if (format === "json") {
    return JSON.stringify(sections, null, 2);
  }

  if (format === "plaintext") {
    return sections
      .map(
        (s) =>
          `${s.title}\n${"-".repeat(s.title.length)}\n` +
          s.commits.map((c) => `  * ${c.message} (${c.sha.slice(0, 7)})`).join("\n")
      )
      .join("\n\n");
  }

  // Default: markdown
  return sections
    .map(
      (s) =>
        `## ${s.title}\n\n` +
        s.commits
          .map(
            (c) =>
              `- ${c.message} [\`${c.sha.slice(0, 7)}\`](https://github.com/${repo}/commit/${c.sha})`
          )
          .join("\n")
    )
    .join("\n\n");
}
